# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/any/all/any.rbi
#
# any-0.1.0
class Any
  def self.==(other); end
  def self.===(other); end
  def self.to_proc; end
end
