# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi gems

# typed: strong
#
# If you would like to make changes to this file, great! Please create the gem's shim here:
#
#   https://github.com/sorbet/sorbet-typed/new/master?filename=lib/polyglot/all/polyglot.rbi
#
# polyglot-0.3.5
module Polyglot
  def self.find(file, *options, &block); end
  def self.load(*a, &b); end
  def self.register(extension, klass); end
end
class Polyglot::PolyglotLoadError < LoadError
end
class Polyglot::NestedLoadError < LoadError
  def initialize(le); end
  def reraise; end
end
module Kernel
  def polyglot_original_require(arg0); end
end
