# This file is autogenerated. Do not edit it by hand. Regenerate it with:
#   srb rbi todo

# typed: strong
module Fear::Failure::EXTRACTOR; end
module Fear::Left::EXTRACTOR; end
module Fear::Right::EXTRACTOR; end
module Fear::RightBiased::Left::None; end
module Fear::Struct; end
module Fear::Struct; end
module Fear::Struct; end
module Fear::Struct; end
module Fear::Success::EXTRACTOR; end
