name: Fear

on:
  pull_request:
  push:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  standard:
    name: Standard 👮
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@eecb3f730879f5b8830705348c2961e5aa26de78 # v1.5.0
        with:
          autofix: false

  specs:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2', "3.3", "3.4", "truffleruby+graalvm-head" ]
    name: Specs on Ruby ${{ matrix.ruby }} 💚
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
      - name: Set up ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Specs
        run: bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # v2.3.6
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ruby-${{ matrix.ruby }}
          parallel: true

  release:
    name: Release Ruby Gem 📦
    runs-on: ubuntu-latest
    environment: release
    needs: [specs, standard]
    if: github.ref == 'refs/heads/master'
    permissions:
      id-token: write # this permission is mandatory for trusted publishing
      contents: write # this permission is required for `rake release` to push the release tag
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@08c6903cd8c0fde910a37f88322edcfb5dd907a8 # v5.0.0
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@44511735964dcb71245e7e55f72539531f7bc0eb # v1.257.0
        with:
          bundler-cache: true
          ruby-version: ruby

      - name: Release Gem
        uses: rubygems/release-gem@ebe1ec66bd8d2c709ac29aa2b43438d450e7a0a6 # v1

  finish:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
    needs: specs
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@f4a75cfd619ee5ce8d5b864b0d183aff3c69b55a # v2.13.1
        with:
          egress-policy: audit

      - name: Coveralls Finished
        uses: coverallsapp/github-action@648a8eb78e6d50909eff900e4ec85cab4524a45b # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
