name: Fear

on:
  pull_request:
  push:
    branches: [ master ]

permissions:  # added using https://github.com/step-security/secure-repo
  contents: read

jobs:
  standard:
    name: Standard 👮
    runs-on: ubuntu-latest
    permissions:
      checks: write
      contents: read
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Standard Ruby
        uses: standardrb/standard-ruby-action@eecb3f730879f5b8830705348c2961e5aa26de78 # v1.5.0
        with:
          autofix: false

  specs:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
      contents: read  # for actions/checkout to fetch code
    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby: [ '3.2', "3.3", "3.4", "truffleruby+graalvm-head" ]
    name: Specs on Ruby ${{ matrix.ruby }} 💚
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
      - name: Set up ruby
        uses: ruby/setup-ruby@2a7b30092b0caf9c046252510f9273b4875f3db9 # v1.254.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Specs
        run: bundle exec rspec
      - name: Coveralls
        uses: coverallsapp/github-action@8cbef1dea373ebce56de0a14c68d6267baa10b44 # v1.1.2
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          flag-name: ruby-${{ matrix.ruby }}
          parallel: true

  release:
    name: Release Ruby Gem 📦
    runs-on: ubuntu-latest
    environment: release
    needs: [specs, standard]
    if: github.ref == 'refs/heads/master'
    permissions:
      id-token: write # this permission is mandatory for trusted publishing
      contents: write # this permission is required for `rake release` to push the release tag
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Checkout code
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: Set up Ruby
        uses: ruby/setup-ruby@bb6434c747fa7022e12fa1cae2a0951fcffcff26 # v1.253.0
        with:
          bundler-cache: true
          ruby-version: ruby

      - name: Release Gem
        uses: rubygems/release-gem@ebe1ec66bd8d2c709ac29aa2b43438d450e7a0a6 # v1

  finish:
    permissions:
      checks: write  # for coverallsapp/github-action to create new checks
    needs: specs
    runs-on: ubuntu-latest
    steps:
      - name: Harden the runner (Audit all outbound calls)
        uses: step-security/harden-runner@ec9f2d5744a09debf3a187a3f4f675c53b671911 # v2.13.0
        with:
          egress-policy: audit

      - name: Coveralls Finished
        uses: coverallsapp/github-action@09b709cf6a16e30b0808ba050c7a6e8a5ef13f8d # master
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          parallel-finished: true
