name: Ruby

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        ruby:
          - '2.4.x'
          - '2.5.x'
          - '2.6.x'
          - '2.7'
    name: ${{ matrix.ruby }}
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up ruby
      uses: actions/setup-ruby@v1
      with:
        ruby-version: ${{ matrix.ruby }}
    - name: Install dependencies
      run: |
        gem install bundler --force --version=2.0.1
        bundler --version
        bundle install --jobs 4 --retry 3
    - name: Test
      run: |
        bundle exec rspec
    - name: Lint
      run: |
        bundle exec rubocop --fail-level C
